### ISSUE TITLE
Proposal to Archive the repo

### ISSUE THREAD

**Issue by maarten-boot** [mboot-github/python-whois#322]
I suggest that we should start thinking about archiving this repository now that no new releases are being made anymore.
This would clearly signal that maintenance has stopped on this repository. 

We could update the readme to reflect the archived status and possibly point to https://github.com/mboot-github/WhoisDomain as its permanent new place of development

I will keep syncing this repository with relevant changes from WhoisDomain until February 3 2024

**Comment by kaloomte** [comment]
I think this is a good idea. For newcomers to the repository, confusion can arise about which repository is following.

**Comment by DannyCork** [comment]
Good idea. You have been the main contributor, thank you.

Instead of archiving python-whois, I propose that I transfer the repo ownership and py-py account to you @maarten-boot maarten-boot. That way the project lives on.

**Comment by maarten-boot** [comment]
Excellent thanks.

**Comment by DannyCork** [comment]
Hi @maarten-boot 
I tried but can't while your cloned repo still exists
<img width="578" alt="image" src="https://github.com/DannyCork/python-whois/assets/3512672/70800805-2ce9-4215-850f-fb8ef38381ae">

**Comment by maarten-boot** [comment]
Best after december 17, im currently on holiday without proper access

**Comment by maarten-boot** [comment]
the fork has now been deleted, feel free to try again

**Comment by DannyCork** [comment]
Thanks Maarten.

**Comment by DannyCork** [comment]
You will also need the pypi project.

**Comment by maarten-boot** [comment]
i now have the repo, how do we do the pypi part

**Comment by maarten-boot** [comment]
the pypi is on the mboot account

https://pypi.org/user/mboot/

**Comment by maarten-boot** [comment]
yep i have now owner access to 
https://pypi.org/project/whois/
